#!/bin/bash
[ -n "$FruitShareCodes" ] && {
  FRUITSHARECODES="$FruitShareCodes"
}
[ -n "$PetShareCodes" ] && {
  PETSHARECODES="$PetShareCodes"
}
[ -n "$SuperMarketShareCodes" ] && {
  SUPERMARKET_SHARECODES="$SuperMarketShareCodes"
}
[ "$FRUITSHARECODES" == "" ] && {
  FRUITSHARECODES=cb4246716771424bbcf95ddc538f045b@f811d0cd0b014e2bbc1074dfc7d76730@500832637d234f4c88c82195a328b6fe
}
[ "$PETSHARECODES" == "" ] && {
  PETSHARECODES=MTE1NDQ5MzYwMDAwMDAwMzcwMDk1ODM=@MTE1NDUyMjEwMDAwMDAwMzcwNjQ5MTM=@MTE1NDQ5OTIwMDAwMDAwMzg5NzM5NTk=
}
[ "$PLANT_BEAN_SHARECODES" == "" ] && {
  PLANT_BEAN_SHARECODES=mlrdw3aw26j3xvmulpdlkkt32g35trpagxwrbca@7oivz2mjbmnx5jrk3p2gxuwdvrorc62cj47lsra@3l3mtwitnfszzjhqa76ilptd54
}
[ "$SUPERMARKET_SHARECODES" == "" ] && {
  SUPERMARKET_SHARECODES=eU9Yae3mYKkkp23QyCEWgg@eU9YOo7gOJxgsgyQgSdL@eU9YDZ_2I518sBuxnjt0@eU9YN732JrpGiBWjnyFP
}
[ "$DDFACTORY_SHARECODES" == "" ] && {
  DDFACTORY_SHARECODES=T0225KkcRR9N8wHVdhnxl6UPIACjVWnYaS5kRrbA@T0205KkcG09dtRK3WWGCwKVWCjVWnYaS5kRrbA@T0084rQsBF1cCjVWnYaS5kRrbA
}
[ "$DREAM_FACTORY_SHARE_CODES" == "" ] && {
  DREAM_FACTORY_SHARE_CODES=RwEfsbJkJ1Y_Ns6wXri2xQ==
}
[ "$JDZZ_SHARECODES" == "" ] && {
  JDZZ_SHARECODES=S5KkcRR9N8wHVdhnxl6UPIA@S5KkcG09dtRK3WWGCwKVW@S4rQsBF1c
}
[ "$JDJOY_SHARECODES" == "" ] && {
  JDJOY_SHARECODES=mwMkvam1uGjxN4HVJKaLOqt9zd5YaBeE@nvGCi1cX_lvpq-RpXL9Yag==@pX4xdaeM4f4=
}

FruitShareCodes=$FRUITSHARECODES
jdJoyRewardNotify=$JD_JOY_REWARD_NOTIFY
jdSuperMarketRewardNotify=$MARKET_REWARD_NOTIFY
joyRunFlag=$JOY_RUN_FLAG
jdSuperMarketUpgrade=$SUPERMARKET_UPGRADE
jdBusinessCircleJump=$BUSINESS_CIRCLE_JUMP
jdSuperMarketLottery=$SUPERMARKET_LOTTERY
jdFruitBeanCard=$FRUIT_BEAN_CARD
